### ISSUE TITLE
Homework 1 Pablo Gonzalez

### ISSUE THREAD

**Issue by pgonzalez6** [pgonzalez6/stat679work#1]
Homework 1, including part 1 and 2. I'm still working on part 3. My apologies for late, but I'm still understanding github functions. 

https://github.com/pgonzalez6/stat679work/commit/c2f6b53ef11d7f383e8a3f513c79646302f4b985

@cecileane 

I'm not sure what is showing you, my code looks like this one:
# Exercise 1
# !/bin/bash

for i in {1..9};do  
cp timetest${i}_snaq.out timetest0${i}_snaq.out
rm timetest${i}_snaq.out
done
## Exercise 2
# !/bin/bash

echo analysis,Hmax,CPU> output.csv
for i in log/*.log;
do
    echo "i=$i" 
    analysis=$(echo $i | grep -o -E "[^/]+.log" | grep -o -E "[^.log]+")
    h=$(grep "hmax" $i | head -n1 | grep -o -E "[0-9]")
    CPU=$(grep -E "Elapsed time. \d+" -o out/$analysis.out) 
    echo "analysis=$analysis ; h=$h ; CPU=$CPU "
    echo "$analysis,$h,$CPU" >> output.csv  
done

**Comment by cecileane** [comment]
Hi Pablo,

Nice work! Some feedback below, that might be helpful for future work.

Your normalization script is lean, this is great. You could have simplified it even more, by combining the 2 commands: `cp` and `rm` with a single command: `mv`. In other words, if you replace
`cp timetest${i}_snaq.out timetest0${i}_snaq.out`
by
`mv timetest${i}_snaq.out timetest0${i}_snaq.out`,
then there is no need to remove the original file afterwards.

About style: indentation is important to make your code human-readable.
- in your normalization script: it would have been better to place `do` on a new line, and to indent the 2 lines between `do` and `done`.
- in your summarizing script: it would have been best to indent all lines in the same way between `do` and `done`. All are indented the same way, except for the last line in the block (`echo "$analysis,$h,$CPU" >> output.csv`).

Your summarizing script worked just fine. Great!

The only glitch is that there is an extra `Elapsed time:` on each line in the output file, just before the CPU time value. It would have been best to remove these words to have the numerical value only. Also, it would be great to keep the digits after the decimal point.

In your [hw1 folder](https://github.com/pgonzalez6/stat679work/tree/master/hw1), the readme file gives great information, to replicate your successful work. This file is missing a set of 3 backticks (```), to mark the end of your first block of code: after
`cp -r Desktop/coursedata/hw1-snaqTimeTests/log stat679work/hw1/` on line 6,
replace # by ``` to end your code block. All the code block between "Exercise 1" and "Exercise 2" would also be better rendered if you could put it in between ``` marks (one set before the code to open the block, another after the code to end the block). Same thing for the code block in the section "Script summarizeSNaQres.sh". Then commit your changes, push them to github, and check how your readme file is rendered [here](https://github.com/pgonzalez6/stat679work/tree/master/hw1).

Your readme file looks strange in your github repository [here](https://github.com/pgonzalez6/stat679work). This file can be viewed in its "raw" form [here](https://raw.githubusercontent.com/pgonzalez6/stat679work/master/README.md). The marks "<<<<<<< HEAD" then "======" then ">>>>>>> origin/master" are marks added by git when there is a conflict between 2 versions that you wanted to merge. You have to edit the file yourself to remove these marks and to edit the file the way you want. It looks like there has been 2 merge conflicts that you have not edited away. Edit this file to provide useful information instead.

You are also tracking a file named "out5.csv" on your [repository](https://github.com/pgonzalez6/stat679work). This file looks like some temporary attempt. It would be best to remove it from your directory and from what git is tracking. You `git rm out5.csv`
to do it.
